# Generated by Django 4.2 on 2024-05-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('placeOfOrigin', models.CharField(max_length=100)),
                ('museum', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('collectionUrl', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Artifact',
                'managed': False,
            },
        ),
    ]
