# Generated by Django 4.2 on 2024-05-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artifact',
            table='artifacts',
        ),
    ]
